name: deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  auto_organization:
    runs-on: windows-latest
    name: Auto Organization
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto Organization Message
        run: echo "Auto Organization"

      - name: Run Deployment Script
        run: |
          Write-Host "Running deployment script ..."
          & "$GITHUB_WORKSPACE/deployment/main.ps1"
