name: deployment
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*

jobs:
    auto_organization:
        runs-on: ubuntu-latest
        name: Auto Organization
        env:
            source: "$GITHUB_WORKSPACE/deployment"
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Auto Organization Message
              run: echo "Auto Organization"

            - name: Run Deployment Script
              run: |
                  echo "Running deployment script $source..."
                  bash "$source/main.sh"
